### ISSUE TITLE
Create a Movies table CRUD system

### ISSUE THREAD

**Issue by unbreaking-V** [unbreaking-V/Movie-Mastermind#1]
# Description: 
We need to create a CRUD system for a Movies table in our database. This will allow us to add, edit, view, and delete movies from the database.

## Tasks:

- [x] Create a function in order to view columns of movies table:  title, genre and rating .
- [x] Implement a "Insert" feature that allows users to add new movies to the database.
- [x] Implement an "Update" feature that allows users to edit existing movie records in the database.
- [x] Implement a "Delete" feature that allows users to remove movies from the database.
